name = "Create Kinetic Horizons"
author = "Shipley7701"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eaeb81ce53491bf8206feb23693a2296ab711f1209779d442285c890ca890d72"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
