name = "Create Kinetic Horizons"
author = "Shipley7701"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20003514b95e892656a9b188f0044d40c941b9681d60b49d00aea6c9c90d4d6b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
