name = "Create Kinetic Horizons"
author = "Shipley7701"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f581318bb0da176c664040b2477324108ccfc495490ff10ec5b088a703046712"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
